### ISSUE TITLE
I anm not able to install pakages it gives me an error

### ISSUE THREAD

**Issue by Prayag8585** [NICK-FURY-6023/muzox-bot-clone#7]
Plz solve this problem

**Comment by NICK-FURY-6023** [comment]
ok share with me  your error

**Comment by Prayag8585** [comment]
![Screenshot_20240301-103001_Chrome](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/88706191/d7e01762-63ea-43d8-9421-1f608299f2ae)

This is the error. It says app is crashed and doesn't start the bot

**Comment by NICK-FURY-6023** [comment]
[now check follwing steps](https://github.com/NICK-FURY-6023/muzox-bot-clone/blob/main/README.md)

**Comment by Prayag8585** [comment]
![Screenshot_20240301-124058_Chrome](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/88706191/5802743f-2f86-4e61-ac14-ab1ca97360c4)
Now I made a new project and this is the problem I am occurring now.
