### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Limeamir** [NICK-FURY-6023/muzox-bot-clone#83]
npm error A complete log of this run can be found in: C:\Users\Пользователь\AppData\Local\npm-cache\_logs\2024-06-25T20_44_53_330Z-debug-0.log
PS C:\Users\Пользователь> cd I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8
PS I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8> npm i
npm warn skipping integrity check for git dependency ssh://git@github.com/Deivu/Shoukaku.git
npm warn skipping integrity check for git dependency ssh://git@github.com/meister03/discord-hybrid-sharding.git
⠼(node:11816) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
npm warn deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm error code 1
npm error path I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build --update-binary
npm error Failed to execute 'E:\node js\node.exe E:\node js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm error node-pre-gyp info it worked if it ends with ok
npm error node-pre-gyp info using node-pre-gyp@1.0.10
npm error node-pre-gyp info using node@22.2.0 | win32 | x64
npm error (node:7500) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
npm error (node:7500) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
npm error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
npm error node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@22.2.0 (node-v127 ABI, unknown) (falling back to source compile with node-gyp)
npm error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-win32-unknown-x64.tar.gz
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.2.0 | win32 | x64
npm error gyp info ok
npm error gyp info it worked if it ends with ok
npm error gyp info using node-gyp@10.1.0
npm error gyp info using node@22.2.0 | win32 | x64
npm error gyp info find Python using Python version 3.11.3 found at "C:\Users\Пользователь\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe"
npm error gyp ERR! find VS
npm error gyp ERR! find VS msvs_version not set from command line or npm config
npm error gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
npm error gyp ERR! find VS
npm error gyp ERR! find VS Failure details: undefined
npm error gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details.
npm error gyp ERR! find VS
npm error gyp ERR! find VS Failure details: undefined
npm error gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
npm error gyp ERR! find VS not looking for VS2017 as it is only supported up to Node.js 21
npm error gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
npm error gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm error gyp ERR! find VS
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS You need to install the latest version of Visual Studio
npm error gyp ERR! find VS including the "Desktop development with C++" workload.
npm error gyp ERR! find VS For more information consult the documentation at:
npm error gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm error gyp ERR! find VS **************************************************************
npm error gyp ERR! find VS
npm error gyp ERR! configure error
npm error gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm error gyp ERR! stack at VisualStudioFinder.fail (E:\node js\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:116:11)
npm error gyp ERR! stack at VisualStudioFinder.findVisualStudio (E:\node js\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:72:17)
npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm error gyp ERR! stack at async createBuildDir (E:\node js\node_modules\npm\node_modules\node-gyp\lib\configure.js:95:26)
npm error gyp ERR! stack at async run (E:\node js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js:81:18)
npm error gyp ERR! System Windows_NT 10.0.19044
npm error gyp ERR! command "E:\\node js\\node.exe" "E:\\node js\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=I:\\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=I:\\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\\node_modules\\canvas\\build\\Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v127"
npm error gyp ERR! cwd I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas
npm error gyp ERR! node -v v22.2.0
npm error gyp ERR! node-gyp -v v10.1.0
npm error gyp ERR! not ok
npm error node-pre-gyp ERR! build error
npm error node-pre-gyp ERR! stack Error: Failed to execute 'E:\node js\node.exe E:\node js\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --update-binary --module=I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas\build\Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v127' (1)
npm error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\@mapbox\node-pre-gyp\lib\util\compile.js:89:23)
npm error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm error node-pre-gyp ERR! System Windows_NT 10.0.19044
npm error node-pre-gyp ERR! command "E:\\node js\\node.exe" "I:\\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm error node-pre-gyp ERR! cwd I:\muzox-bot-clone-dependabot-npm_and_yarn-types-node-20.14.8\node_modules\canvas
npm error node-pre-gyp ERR! node -v v22.2.0
npm error node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm error node-pre-gyp ERR! not ok

**Comment by NICK-FURY-6023** [comment]
This package is no longer supported. 

installl leatest package

**Comment by Limeamir** [comment]
how
