### ISSUE TITLE
Error for starting

### ISSUE THREAD

**Issue by Limeamir** [NICK-FURY-6023/muzox-bot-clone#86]
![image](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/170571364/0972839e-750f-4710-bfcf-a96334286e22)
![image](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/170571364/cfd36b5c-404c-4bde-828b-3782fa66b0b5)
![image](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/170571364/c8cc2a39-f20e-44d7-82da-a0c659207528)
![image](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/170571364/6269c0b8-757f-4414-b5b2-2957a37ed20a)
![image](https://github.com/NICK-FURY-6023/muzox-bot-clone/assets/170571364/cf6ab13a-ced3-43fc-9b61-a31cfea598d8)
How fix it

**Comment by NICK-FURY-6023** [comment]
It's not complete bro it's under development
